FROM golang:1.23 AS builder

WORKDIR /src/
ENV CGO_ENABLED=0
ENV CGO_CFLAGS="-Wno-return-local-addr"
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bookworm
EXPOSE 3000

WORKDIR /app/
COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]
