FROM node:22-bookworm AS builder

RUN corepack enable

WORKDIR /app/webui

COPY webui/.yarnrc.yml ./
COPY webui/.yarn ./.yarn
COPY webui/package.json webui/yarn.lock ./

RUN yarn install

COPY webui/ .

RUN yarn run build-prod

FROM nginx:stable

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/webui/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
