FROM golang:1.25 AS builder

WORKDIR /src/
ENV CGO_ENABLED=0
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bookworm
EXPOSE 3000

WORKDIR /app/
RUN mkdir -p /app/data
COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]
