server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /sse {
        proxy_pass http://backend:3000;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 24h;
    }

    location /send {
        proxy_pass http://backend:3000;
    }
}
