openapi: 3.0.0
info:
  title: WASAText
  description: |
    API for WASAText, which is a online messaging application
    similar to whatsapp
  version: 1.0.0

components:
  schemas:

    message:
      description: a single message
      type: object
      properties:
        id:
          type: integer
        status:
          description: status of the message
          type: string
          enum: [unknown, received, read]
        content:
          description: the content of the message, string or a file
          oneOf:
            - type: string
            - type: string
          format: binary
        comment:
          description: emoticon for the message
          type: array
          items:
            type: integer
        timestamp:
          description: time when the message was sent
          type: string
          format: date-time
          example: '2019-10-19 17:12:30'
        sender:
          description: user who sent the message
          type: integer
        conversation:
          description: conversation that the message belongs to
          type: integer

    conversation:
      description: a conversation head
      type: object
      properties:
        id:
          type: integer
        snippet:
          description: snippet of the last message, string or picture
          oneOf:
            - type: string
            - type: string
          format: binary
        name:
          description: name of the sender, username or group name
          oneOf:
            - $ref: "#/components/schemas/user/properties/name"
            - type: string
        picture:
          description: picture of the user or group
          $ref: "#/components/schemas/user/properties/picture"
        date:
          description: time when the last message was sent
          type: string
          format: date-time
          example: '2019-10-19 17:12:30'
        content:
          description: content of the  conversation
          type: array
          items:
            $ref: "#/components/schemas/message"
        groupchat:
          description: if it is group or not
          type: boolean
        members:
          description: members of the group
          type: array
          items:
            type: integer

    user:
      description: a single user
      type: object
      properties:
        id:
          type: integer
        name:
          description: name of the user
          type: string
        picture:
          description: picture of the user
          type: string
          format: binary
        conversations:
          description: list of all conversations
          type: array
          items:
            type: integer

    comment:
      description: a comment for the message
      type: object
      properties:
        id:
          type: integer
        content:
          description: emoticon
        user:
          description: user who added the comment
          $ref: "#/components/schemas/user/properties/name"
  parameters:
    userId:
      description: identifier for the user
      name: Id
      in: path
      required: true
      schema:
        type: integer

    conversationId:
      description: identifier for the conversation
      name: conversationId
      in: path
      required: true
      schema:
        type: integer

    messageId:
      description: identifier for the message
      name: messageId
      in: path
      required: true
      schema:
        type: integer

    commentId:
      description: identifier for the comment
      name: commentId
      in: path
      required: true
      schema:
        type: integer




paths:

  /session:
    post:
      tags:
        - login
      summary: Logs in the user
      description: >-
        if the user does not exist, it will be created and an identifier is
        returned.

        IF the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: ^.*?$
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: abcdef012345



  /mainpage/{Id}:
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      operationId: getSelf
      description: get the user
      responses:
        "200":
          description: user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"


  /mainpage/{Id}/users:
    parameters:
      - $ref : "#/components/parameters/userId"
    get:
      operationId: getUsers
      description: lists all the users
      responses:
        "200":
          description: an array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user/properties/name"

  /mainpage/{Id}/users/specificUser:
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      operationId: getSpecificUser
      description: from the list of users search for a specific user
      responses:
        "200":
          description: a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "404":
          description: user not found


  /mainpage/{Id}/settings/name:
    parameters:
      - $ref: "#/components/parameters/userId"
    put:
      operationId: setMyUserName
      description: change the name of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user/properties/name"

      responses:
        "204":
          description: successfully changed the name
        "400":
          description: could not change into this name

  /mainpage/{Id}/settings/picture:
    parameters:
      - $ref: "#/components/parameters/userId"
    put:
      operationId: setMyPhoto
      description: change the picture of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user/properties/picture"
      responses:
        "204":
          description: successfully changed the picture
        "400":
          description: could not change the picture

  /mainpage/{Id}/conversations:
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      operationId: getMyConversations
      description: list all my conversations
      parameters:
        - in: query
          required: false
          $ref: "#/components/parameters/conversationId"
      responses:
        "200":
          description: array of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/conversation"
    post:
      operationId: startNewConversation
      description: start a new conversation with a user by name, or a group
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/user/properties/name"
      responses:
        "201":
          description: conversation successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conversation/properties/id'
        "403":
          description: user not found

  /mainpage/{Id}/conversations/{conversationId}:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
    get:
      operationId: getConversation
      description: get a specific conversation
      responses:
        "200":
          description: object conversation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/conversation"
        "404":
          description: conversation not found
    post:
      operationId: sendMessage
      description: send a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message/properties/content"
      responses:
        "201":
          description: message successfully sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message/properties/id"

  /mainpage/{Id}/conversations/{conversationId}/conversationsettings/groupname:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
    put:
      operationId: setGroupName
      description: change the name of the group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/conversation/properties/name"
      responses:
        "204":
          description: successfully changed the name
        "400":
          description: name could not be changed

  /mainpage/{Id}/conversations/{conversationId}/conversationsettings/grouppicture:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
    put:
      operationId: setGroupPhoto
      description: change the picture of the group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/conversation/properties/picture"
      responses:
        "204":
          description: successfully changed the picture

  /mainpage/{Id}/conversations/{conversationId}/{messageId}:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
      - $ref : "#/components/parameters/messageId"
    delete:
      operationId: deleteMessage
      description: delete my message
      responses:
        "200":
          description: message successfully deleted
        "404":
          description: message not found
    get:
      operationId: getMessage
      description: get a specific message
      responses:
        "200":
          description: object message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message"
        "404":
          description: message not found
    post:
      operationId: forwardMessage
      description: forward the message to other conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/conversation/properties/name"
      responses:
        "201":
          description: message successfully forwarded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message/properties/id"
        "404":
          description: could not find the user

  /mainpage/{Id}/conversations/{conversationId}/{messageId}/comments:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
      - $ref : "#/components/parameters/messageId"
    get:
      operationId: getComments
      description: get all comments for this message
      responses:
        "200":
          description: array of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/comment"
    post:
      operationId: commentMessage
      description: add a new comment on this message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/comment/properties/content"
      responses:
        "201":
          description: comment successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment/properties/id"

  /mainpage/{Id}/conversations/{conversationId}/{messageId}/comments/{commentId}:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
      - $ref : "#/components/parameters/messageId"
      - $ref : "#/components/parameters/commentId"
    get:
      operationId: getSpecificComment
      description: get a specific comment for this message
      responses:
        "200":
          description: a comment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment"
        "404":
          description: comment not found
    delete:
      operationId: uncommentMessage
      description: delete my comment
      responses:
        "200":
          description: comment successfully deleted
        "404":
          description: comment not found

  /mainpage/{Id}/conversations/{conversationId}/groupMembers:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/conversationId"
    get:
      operationId: listGroupMembers
      description: see all the group members
      responses:
        "200":
          description: array of group member names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user/properties/name"
    post:
      operationId: addToGroup
      description: add a member to the group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user/properties/name"
      responses:
        "201":
          description: user successfully added
        "404":
          description: user not found
    delete:
      operationId: leaveGroup
      description: leave this group
      responses:
        "200":
          description: left the group
        "404":
          description: group not found
