openapi: 3.0.0
info:
  title: WASAText
  description: |
    API for WASAText, which is a online messaging application 
    similar to whatsapp
  version: 1.0.0

components:
    schemas:
        messages:
            description:
                a single message
            type: object
            properties:
                id:
                    description: identifier for the message
                    type: integer
                status:
                    description: status of the message
                    type: string
                    enum: [unknown, received, read]
                content:
                    description: the content of the message, string or a file
                    oneOf:
                    - type: string
                    - type: string
                    format: binary
                comment:
                    description: emoticon for the message
                    type: array
                    items: 
                        $ref: "#/components/schemas/comment"
                timestamp:
                    description: time when the message was sent
                    type: string
                    format: date-time
                    example: '2019-10-19 17:12:30'
                user:
                    description: user who sent the message
                    $ref: "#/components/schemas/user/properties/name"


            
        conversation:
            description: a conversation head
            type: object
            properties:
                id:
                    description: identifier for the conversation
                    type: integer
                snippet:
                    description: snippet of the last message, string or picture
                    oneOf:
                    - type: string
                    - type: string
                    format: binary
                name:
                    description: name of the sender, username or group name
                    oneOf:
                    - $ref: "#/components/schemas/user/properties/name"
                    - type: string
                picture:
                    description: picture of the user or group
                    $ref: "#/components/schemas/user/properties/picture"
                date:                    
                    description: time when the last message was sent
                    type: string
                    format: date-time
                    example: '2019-10-19 17:12:30'
                content:
                    description: content of the  conversation
                    type: array
                    items: 
                        $ref: "#/components/schemas/messages"
        user:
            description: a single user
            type: object
            properties:
                id:
                    description: identifier for the user
                    type: integer
                name:
                    description: name of the user
                    type: string
                picture:
                    description: picture of the user
                    type: string
                    format: binary
        comment:
            description: a comment for the message
            type: object
            properties:
                id:
                    description: identifier for the comment
                    type: integer
                content:
                    description: emoticon
                user:
                    description: user who added the comment
                    $ref: "#/components/schemas/user/properties/name"
paths:
    /session:
        post:
            tags:
                - login
            summary: Logs in the user
            description: >-
                if the user does not exist, it will be created and an identifier is
                returned.

                IF the user exists, the user identifier is returned.
            operationId: doLogin
            requestBody:
                description: User details
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    example: Maria
                                    pattern: ^.*?$
                                    minLength: 3
                                    maxLength: 16
                required: true
            responses:
                '201':
                    description: User log-in action successful
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    identifier:
                                        type: string
                                        example: abcdef012345
    /mainpageId:
        get:
            operationId: getUsers
            description: lists all the users
            responses:
                "200":
                    description: an array of users
                    content:
                        application/json:
                            schema:
                                type: array
                                items: 
                                    $ref: "#/components/schemas/user/properties/name"
        
    /mainpageId/settings/name:
        put:
            operationId: setMyUserName
            description: change the name of the user
            responses:
                "200":
                    description: successfully changed the name
                "403":
                    description: name already in use by a different user
    /mainpageId/settings/picture:
        put:
            operationId: setMyPhoto
            description: change the picture of the user
            responses:
                "200":
                    description: successfully changed the picture
    /mainpageId/conversations:
        get:
            operationId: getMyConversations
            description: list all my conversations
            responses:
                "200":
                    description: array of conversations
                    content:
                        application/json:
                            schema:
                                type: array
                                items: 
                                    $ref: "#/components/schemas/conversation"
        post:
            operationId: startNewConversation
            description: start a new conversation with a user by name
            responses:
                "200":
                    description: conversation successfully created
                "403":
                    description: user not found
    /mainpageId/conversations/conversationId:
        get:
            operationId: getConversation
            description: get a specific conversation
            responses:
                "200":
                    description: object conversation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/conversation"
        post:
            operationId: sendMessage
            description: send a new message
            responses:
                "201":
                    description: message successfully sent
    /mainpageId/conversations/conversationId/conversationsettings/groupname:
        put:
            operationId: setGroupName
            description: change the name of the group
            responses:
                "200":
                    description: successfully changed the name
    /mainpageId/conversations/conversationId/conversationsettings/grouppicture:
        put:
            operationId: setGroupPhoto
            description: change the picture of the group
            responses:
                "200":
                    description: successfully changed the picture
    /mainpageId/conversations/conversationId/messageId:
        delete:
            operationId: deleteMessage
            description: delete my message
            responses:
                "204":
                    description: message successfully deleted
        get:
            operationId: getMessage
            description: get a specific message
            responses:
                "200":
                    description: object message
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messages"
        post:
            operationId: forwardMessage
            description: forward the message to other conversation
            responses:
                "201":
                    description: message successfully forwarded
    /mainpageId/conversations/conversationId/messageId/comments:
        get:
            operationId: getComments
            description: get all comments for this message
            responses:
                "200":
                    description: array of comments
                    content:
                        application/json:
                            schema:
                                type: array
                                items: 
                                    $ref: "#/components/schemas/comment"
        post:
            operationId: commentMessage
            description: add a new comment on this message
            responses:
                "201":
                    description: comment successfully added
    /mainpageId/conversations/conversationId/messageId/comments/commentId:
        delete:
            operationId: uncommentMessage
            description: delete my comment
            responses:
                "204":
                    description: comment successfully deleted
    /mainpageId/conversations/conversationId/groupMembers:
        post:
            operationId: addToGroup
            description: add a member to the group
            responses:
                "201":
                    description: user successfully added
        delete:
            operationId: leaveGroup
            description: leave this group
            responses:
                "204":
                    description: left the group

      allowEmptyValue: false
